name: bke
description: bke.com

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.5
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  # curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  flutter_screenutil: ^5.5.3+2
  flutter_keyboard_visibility: ^5.3.0
  flutter_secure_storage: ^6.0.0
  flutter_facebook_auth: ^4.4.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  html: ^0.15.0
  infinite_scroll_pagination: ^3.2.0
  like_button: ^2.0.4
  lottie: ^1.3.0
  logger: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  pinput: ^2.2.11
  scroll_to_index: ^3.0.1
  string_validator: ^0.3.0
  simple_html_css: ^4.0.0
  skeletons: ^0.0.3
  scrollable_positioned_list: ^0.3.5
  translator: ^0.1.7
  youtube_player_flutter: ^8.1.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/authentication/
    - assets/icons/
    - assets/images/
    - assets/texture/