name: bke
description: bke.com

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # assets_audio_player: ^3.0.5
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  # curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.2
  dio: ^5.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^2.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_keyboard_visibility: ^5.3.0
  flutter_secure_storage: ^7.0.1
  flutter_facebook_auth: ^5.0.7
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  html: ^0.15.0
  image_picker: ^0.8.7
  infinite_scroll_pagination: ^3.2.0
  like_button: ^2.0.4
  lottie: ^2.2.0
  logger: ^1.1.0
  pinput: ^2.2.31
  scroll_to_index: ^3.0.1
  string_validator: ^1.0.0
  simple_html_css: ^4.0.0
  skeletons: ^0.0.3
  scrollable_positioned_list: ^0.3.5
  translator: ^0.1.7
  youtube_player_flutter: ^8.1.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^3.0.1
  get_it: ^7.2.0
  font_awesome_flutter: ^10.3.0
  image_pixels: ^3.0.0
  syncfusion_flutter_charts: ^20.4.50
  shared_preferences: ^2.1.0
  dropdown_button2: ^2.0.0
  tuple: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.52
  assets_audio_player: ^3.0.6
  path_provider: ^2.0.13
  table_calendar: ^3.0.7
  url_launcher: ^6.1.10
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.1
  get: ^4.6.5
  intl: ^0.17.0
  flutter_native_splash: ^2.2.19
  firebase_messaging: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/authentication/
    - assets/icons/
    - assets/images/
    - assets/texture/